package com.habsradio.broadcaster;

import android.app.*;import android.content.*;import android.content.pm.ServiceInfo;import android.media.*;import android.media.projection.*;import android.os.*;
import org.json.*;import java.util.*;import java.util.concurrent.*;

public final class BroadcastService extends Service{
 public static final String ACTION_START="com.habsradio.broadcaster.START",ACTION_STOP="com.habsradio.broadcaster.STOP",ACTION_RECONNECT="com.habsradio.broadcaster.RECONNECT",ACTION_STATUS="com.habsradio.broadcaster.STATUS";
 public static final String EXTRA_PROJECTION_CODE="projection_code",EXTRA_PROJECTION_DATA="projection_data",EXTRA_TARGETS_JSON="targets_json",EXTRA_MIC_ENABLED="mic_enabled",EXTRA_MIC_GAIN="mic_gain",EXTRA_STREAM_ID="stream_id";
 private static final String CHANNEL_ID="habs_broadcast";private static final int NOTIFICATION_ID=19081;
 private volatile boolean running,closing;private Thread engineThread,micThread;private MediaProjection projection;private AudioRecord playbackRecord,micRecord;private final Object micLock=new Object();private short[] latestMic=new short[0];private float micGain=.65f;private final LinkedHashMap<String,OutputWorker> outputs=new LinkedHashMap<>();
 @Override public void onCreate(){super.onCreate();NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);if(Build.VERSION.SDK_INT>=26){NotificationChannel ch=new NotificationChannel(CHANNEL_ID,"HABS Broadcast",NotificationManager.IMPORTANCE_LOW);ch.setDescription("HABS DJ and radio broadcast engine");nm.createNotificationChannel(ch);}}
 @Override public int onStartCommand(Intent intent,int flags,int startId){if(intent==null)return START_NOT_STICKY;String action=intent.getAction();if(ACTION_STOP.equals(action)){stopBroadcast("Broadcast stopped");return START_NOT_STICKY;}if(ACTION_RECONNECT.equals(action)){String id=intent.getStringExtra(EXTRA_STREAM_ID);synchronized(outputs){OutputWorker w=outputs.get(id);if(w!=null)w.reconnectNow();}return START_NOT_STICKY;}if(!ACTION_START.equals(action)||running)return START_NOT_STICKY;
   boolean micEnabled=intent.getBooleanExtra(EXTRA_MIC_ENABLED,true);micGain=intent.getFloatExtra(EXTRA_MIC_GAIN,.65f);int types=ServiceInfo.FOREGROUND_SERVICE_TYPE_MEDIA_PROJECTION;if(micEnabled&&Build.VERSION.SDK_INT>=30)types|=ServiceInfo.FOREGROUND_SERVICE_TYPE_MICROPHONE;if(Build.VERSION.SDK_INT>=29)startForeground(NOTIFICATION_ID,notification("Connecting…"),types);else startForeground(NOTIFICATION_ID,notification("Connecting…"));
   int resultCode=intent.getIntExtra(EXTRA_PROJECTION_CODE,Activity.RESULT_CANCELED);Intent data=Build.VERSION.SDK_INT>=33?intent.getParcelableExtra(EXTRA_PROJECTION_DATA,Intent.class):intent.getParcelableExtra(EXTRA_PROJECTION_DATA);String targetsJson=intent.getStringExtra(EXTRA_TARGETS_JSON);if(resultCode!=Activity.RESULT_OK||data==null){BroadcastState.stop("Android did not grant device-audio capture");status();stopSelf();return START_NOT_STICKY;}
   try{JSONArray arr=new JSONArray(targetsJson==null?"[]":targetsJson);List<StreamTarget> ts=new ArrayList<>();for(int i=0;i<arr.length();i++){StreamTarget t=StreamTarget.fromJson(arr.getJSONObject(i));if(t.enabled&&!t.host.isEmpty())ts.add(t);}if(ts.isEmpty())throw new IllegalArgumentException("No enabled streaming destination is configured");BroadcastState.begin(ts);MediaProjectionManager mpm=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);projection=mpm.getMediaProjection(resultCode,data);projection.registerCallback(new MediaProjection.Callback(){@Override public void onStop(){if(!closing)stopBroadcast("Android stopped device-audio capture");}},new Handler(Looper.getMainLooper()));startEngine(ts,micEnabled);}catch(Exception e){BroadcastState.stop(friendly(e));status();stopBroadcast(friendly(e));}return START_NOT_STICKY;}
 private void startEngine(List<StreamTarget> targets,boolean micEnabled)throws Exception{int sampleRate=chooseSampleRate();int min=AudioRecord.getMinBufferSize(sampleRate,AudioFormat.CHANNEL_IN_STEREO,AudioFormat.ENCODING_PCM_16BIT);if(min<=0)min=sampleRate/5*4;int bufferBytes=Math.max(min*3,32768);
   AudioPlaybackCaptureConfiguration cfg=new AudioPlaybackCaptureConfiguration.Builder(projection).addMatchingUsage(AudioAttributes.USAGE_MEDIA).addMatchingUsage(AudioAttributes.USAGE_GAME).addMatchingUsage(AudioAttributes.USAGE_UNKNOWN).build();AudioFormat format=new AudioFormat.Builder().setEncoding(AudioFormat.ENCODING_PCM_16BIT).setSampleRate(sampleRate).setChannelMask(AudioFormat.CHANNEL_IN_STEREO).build();playbackRecord=new AudioRecord.Builder().setAudioPlaybackCaptureConfig(cfg).setAudioFormat(format).setBufferSizeInBytes(bufferBytes).build();if(playbackRecord.getState()!=AudioRecord.STATE_INITIALIZED)throw new IllegalStateException("Android device-audio capture could not initialize");
   running=true;closing=false;if(micEnabled)startMicrophone(sampleRate);synchronized(outputs){outputs.clear();for(StreamTarget t:targets){OutputWorker w=new OutputWorker(t);outputs.put(t.id,w);w.start();}}
   Map<Integer,Mp3Encoder> encoders=new HashMap<>();for(StreamTarget t:targets)encoders.computeIfAbsent(t.bitrate,b->new Mp3Encoder(sampleRate,2,b));playbackRecord.startRecording();BroadcastState.capture(true);status();engineThread=new Thread(()->{short[] pcm=new short[4096];long lastMeter=0;try{while(running){int n=playbackRecord.read(pcm,0,pcm.length,AudioRecord.READ_BLOCKING);if(n<=0)continue;int frames=n/2;mixMic(pcm,frames);float pk=peak(pcm,n);long now=SystemClock.elapsedRealtime();if(now-lastMeter>280){lastMeter=now;BroadcastState.level(dbText(pk));status();}for(Map.Entry<Integer,Mp3Encoder> en:encoders.entrySet()){byte[] mp3=en.getValue().encode(pcm,frames);if(mp3.length==0)continue;synchronized(outputs){for(OutputWorker w:outputs.values())if(w.target.bitrate==en.getKey())w.offer(mp3);}}}}catch(Throwable e){if(running){BroadcastState.stop(friendly(e));status();}}finally{for(Mp3Encoder e:encoders.values()){try{byte[] tail=e.flush();if(tail.length>0)synchronized(outputs){for(OutputWorker w:outputs.values())w.offer(tail);}}catch(Exception ignored){}try{e.close();}catch(Exception ignored){}}if(running)stopBroadcast("Broadcast engine stopped");}},"HABS-Android-Audio");engineThread.start();}
 private int chooseSampleRate(){for(int r:new int[]{48000,44100}){int n=AudioRecord.getMinBufferSize(r,AudioFormat.CHANNEL_IN_STEREO,AudioFormat.ENCODING_PCM_16BIT);if(n>0)return r;}return 48000;}
 private void startMicrophone(int sampleRate){try{int min=AudioRecord.getMinBufferSize(sampleRate,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT);if(min<=0)return;micRecord=new AudioRecord(MediaRecorder.AudioSource.VOICE_RECOGNITION,sampleRate,AudioFormat.CHANNEL_IN_MONO,AudioFormat.ENCODING_PCM_16BIT,Math.max(min*3,16384));if(micRecord.getState()!=AudioRecord.STATE_INITIALIZED){micRecord.release();micRecord=null;return;}micRecord.startRecording();micThread=new Thread(()->{short[] b=new short[2048];while(running&&micRecord!=null){int n=micRecord.read(b,0,b.length,AudioRecord.READ_BLOCKING);if(n>0)synchronized(micLock){latestMic=Arrays.copyOf(b,n);}}},"HABS-Android-Mic");micThread.start();}catch(Throwable ignored){micRecord=null;}}
 private void mixMic(short[] stereo,int frames){short[] mic;synchronized(micLock){mic=latestMic;}if(mic==null||mic.length==0||micGain<=.0001f)return;int count=Math.min(frames,mic.length),start=Math.max(0,mic.length-count);for(int i=0;i<count;i++){int m=(int)(mic[start+i]*micGain),p=i*2;stereo[p]=clip(stereo[p]+m);stereo[p+1]=clip(stereo[p+1]+m);}}
 private static short clip(int v){return(short)Math.max(Short.MIN_VALUE,Math.min(Short.MAX_VALUE,v));}private static float peak(short[] b,int n){int p=0;for(int i=0;i<n;i++)p=Math.max(p,Math.abs((int)b[i]));return p/32768f;}private static String dbText(float x){return x<=.00001f?"-∞ dBFS":String.format(Locale.US,"%.1f dBFS",20.0*Math.log10(x));}
 private synchronized void stopBroadcast(String reason){if(closing)return;closing=true;running=false;BroadcastState.stop(reason);try{if(playbackRecord!=null)playbackRecord.stop();}catch(Exception ignored){}try{if(playbackRecord!=null)playbackRecord.release();}catch(Exception ignored){}playbackRecord=null;try{if(micRecord!=null)micRecord.stop();}catch(Exception ignored){}try{if(micRecord!=null)micRecord.release();}catch(Exception ignored){}micRecord=null;synchronized(outputs){for(OutputWorker w:outputs.values())w.shutdown();outputs.clear();}try{if(projection!=null)projection.stop();}catch(Exception ignored){}projection=null;engineThread=null;BroadcastState.capture(false);status();stopForeground(STOP_FOREGROUND_REMOVE);stopSelf();closing=false;}
 @Override public void onDestroy(){stopBroadcast("Broadcast service closed");super.onDestroy();}@Override public IBinder onBind(Intent i){return null;}
 private Notification notification(String text){Intent launch=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,launch,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);return new Notification.Builder(this,CHANNEL_ID).setSmallIcon(R.drawable.ic_habs).setContentTitle("HABS Broadcaster • Android").setContentText(text).setOngoing(true).setContentIntent(pi).build();}
 private void status(){JSONObject s=BroadcastState.json();Intent i=new Intent(ACTION_STATUS).setPackage(getPackageName());i.putExtra("json",s.toString());sendBroadcast(i);try{NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);String t=s.optBoolean("on_air")?"ON AIR • "+s.optInt("connected_count")+" output(s)":s.optInt("desired_count")>0?"Connecting outputs…":"Off Air";nm.notify(NOTIFICATION_ID,notification(t));}catch(Exception ignored){}}
 private static String friendly(Throwable e){if(e==null)return"Unknown broadcast error";String s=e.getMessage();return s==null||s.trim().isEmpty()?e.getClass().getSimpleName():s;}
 private final class OutputWorker extends Thread{final StreamTarget target;final ArrayBlockingQueue<byte[]> queue=new ArrayBlockingQueue<>(72);volatile boolean alive=true,connected;volatile boolean forceReconnect;IcecastSink sink;int failures;long connectedAt;
   OutputWorker(StreamTarget t){super("HABS-Output-"+t.id);target=t;setDaemon(true);}void offer(byte[] b){if(!alive)return;if(!queue.offer(b)){queue.poll();queue.offer(b);}}void reconnectNow(){forceReconnect=true;try{if(sink!=null)sink.close();}catch(Exception ignored){}interrupt();}
   public void run(){while(alive){try{if(forceReconnect){forceReconnect=false;connected=false;if(sink!=null)sink.close();sink=null;}if(sink==null||!sink.isConnected()){connected=false;sink=new IcecastSink(target);sink.connect();connected=true;connectedAt=SystemClock.elapsedRealtime();failures=0;BroadcastState.connected(target);status();}byte[] data=queue.poll(2,TimeUnit.SECONDS);if(data!=null){sink.write(data);BroadcastState.bytes(target,data.length);}}catch(Throwable e){connected=false;try{if(sink!=null)sink.close();}catch(Exception ignored){}sink=null;BroadcastState.disconnected(target,friendly(e));status();if(!alive)break;if(!target.autoReconnect){alive=false;break;}failures++;long stable=connectedAt==0?0:SystemClock.elapsedRealtime()-connectedAt;if(stable>30000)failures=1;long delay=Math.min(30000,target.reconnectDelay*1000L*(1L<<Math.min(3,Math.max(0,failures-1))));try{Thread.sleep(delay);}catch(InterruptedException ignored){}}}connected=false;try{if(sink!=null)sink.close();}catch(Exception ignored){}}
   void shutdown(){alive=false;interrupt();try{if(sink!=null)sink.close();}catch(Exception ignored){}}
 }
}
