package com.habsradio.broadcaster;

import android.util.Base64;
import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import javax.net.ssl.SSLSocketFactory;

public final class IcecastSink implements AutoCloseable{
 private final StreamTarget target;private Socket socket;private BufferedOutputStream out;private BufferedInputStream in;private volatile boolean connected;
 public IcecastSink(StreamTarget t){target=t;}
 public synchronized void connect() throws IOException{close();Socket raw=target.tls?SSLSocketFactory.getDefault().createSocket():new Socket();raw.connect(new InetSocketAddress(target.host,target.port),target.connectTimeout*1000);raw.setSoTimeout(target.connectTimeout*1000);raw.setKeepAlive(true);raw.setTcpNoDelay(true);socket=raw;out=new BufferedOutputStream(raw.getOutputStream(),64*1024);in=new BufferedInputStream(raw.getInputStream(),16*1024);if(StreamTarget.isShoutcast(target.protocol))connectShoutcast();else connectIcecast();socket.setSoTimeout(0);connected=true;}
 private void connectIcecast()throws IOException{String mount=target.mount==null||target.mount.isEmpty()?"/":target.mount;if(!mount.startsWith("/"))mount="/"+mount;String user=target.username==null||target.username.isEmpty()?"source":target.username;String pass=target.password==null?"":target.password;String auth=Base64.encodeToString((user+":"+pass).getBytes(StandardCharsets.UTF_8),Base64.NO_WRAP);String req="PUT "+mount+" HTTP/1.1\r\n"+"Host: "+target.host+":"+target.port+"\r\n"+"Authorization: Basic "+auth+"\r\n"+"User-Agent: HABS-Broadcaster-Android/1.1\r\n"+"Content-Type: audio/mpeg\r\n"+"Ice-Name: "+safe(target.stationName.isEmpty()?target.name:target.stationName)+"\r\n"+"Ice-Genre: "+safe(target.genre)+"\r\n"+"Ice-URL: "+safe(target.stationUrl)+"\r\n"+"Ice-Description: "+safe(target.description)+"\r\n"+"Ice-Public: "+(target.publicStream?"1":"0")+"\r\n"+"Ice-Bitrate: "+target.bitrate+"\r\n"+"Connection: keep-alive\r\n\r\n";out.write(req.getBytes(StandardCharsets.ISO_8859_1));out.flush();String h=readHeader();if(!(h.contains(" 200 ")||h.startsWith("HTTP/1.0 200")||h.startsWith("HTTP/1.1 200")||h.contains(" 201 ")||h.contains(" 204 ")))throw new IOException(friendly(h));}
 private void connectShoutcast()throws IOException{String pass=target.password==null?"":target.password,user=target.username==null?"":target.username;String login=user.isEmpty()||"source".equalsIgnoreCase(user)?pass:user+":"+pass;if("shoutcast2-compat".equals(target.protocol)&&target.sid>0)login+=":#"+target.sid;String req=login+"\r\n"+"icy-name:"+safe(target.stationName.isEmpty()?target.name:target.stationName)+"\r\n"+"icy-genre:"+safe(target.genre)+"\r\n"+"icy-url:"+safe(target.stationUrl)+"\r\n"+"icy-pub:"+(target.publicStream?"1":"0")+"\r\n"+"icy-br:"+target.bitrate+"\r\n"+"content-type:audio/mpeg\r\n\r\n";out.write(req.getBytes(StandardCharsets.ISO_8859_1));out.flush();byte[] tmp=new byte[512];int n=in.read(tmp);String r=n<=0?"":new String(tmp,0,n,StandardCharsets.ISO_8859_1);if(!(r.startsWith("OK2")||r.startsWith("OK")||r.toLowerCase().contains("icy-caps")))throw new IOException("SHOUTcast rejected the source login: "+compact(r));}
 public synchronized void write(byte[] data)throws IOException{if(!isConnected()||out==null)throw new IOException("Stream is not connected");out.write(data);out.flush();}
 public boolean isConnected(){return connected&&socket!=null&&socket.isConnected()&&!socket.isClosed();}
 private String readHeader()throws IOException{ByteArrayOutputStream b=new ByteArrayOutputStream();int state=0;while(b.size()<32768){int v=in.read();if(v<0)break;b.write(v);if(state==0&&v=='\r')state=1;else if(state==1&&v=='\n')state=2;else if(state==2&&v=='\r')state=3;else if(state==3&&v=='\n')break;else state=v=='\r'?1:0;}return b.toString(StandardCharsets.ISO_8859_1.name());}
 private static String friendly(String h){String c=compact(h),l=c.toLowerCase();if(c.contains("403")&&l.contains("mountpoint"))return "Mountpoint is already in use";if(c.contains("401")||c.contains("403"))return "Streaming credentials were rejected";return "Streaming server rejected the source: "+c;}
 private static String safe(String s){return s==null?"":s.replace("\r"," ").replace("\n"," ");}
 private static String compact(String s){if(s==null||s.trim().isEmpty())return "no response";s=s.replaceAll("\\s+"," ").trim();return s.length()>260?s.substring(0,260)+"…":s;}
 public synchronized void close(){connected=false;try{if(out!=null)out.close();}catch(Exception ignored){}try{if(in!=null)in.close();}catch(Exception ignored){}try{if(socket!=null)socket.close();}catch(Exception ignored){}out=null;in=null;socket=null;}
}
