package com.habsradio.broadcaster;

import android.content.*;import android.net.Uri;import android.webkit.MimeTypeMap;import fi.iki.elonen.NanoHTTPD;import org.json.*;
import java.io.*;import java.nio.charset.StandardCharsets;import java.security.SecureRandom;import java.util.*;import java.util.concurrent.*;

public final class LocalServer extends NanoHTTPD{
 private final Context context;private final ActivationClient activation;private final SpotifyBridge spotify=new SpotifyBridge();private final String localToken=randomToken();private volatile ActivationClient.Session session;private volatile long lastValidated;private final File musicDir;private final Deque<String> logs=new ArrayDeque<>();
 public LocalServer(Context c,int port)throws IOException{super("127.0.0.1",port);context=c.getApplicationContext();activation=new ActivationClient(context);musicDir=new File(context.getFilesDir(),"music");if(!musicDir.exists())musicDir.mkdirs();start(SOCKET_READ_TIMEOUT,false);log("HABS Android local control server started on 127.0.0.1:"+port);}
 public String baseUrl(){return "http://127.0.0.1:"+getListeningPort();}
 public ActivationClient.Session activationSession(){return session;}
 private static String randomToken(){byte[] b=new byte[24];new SecureRandom().nextBytes(b);return android.util.Base64.encodeToString(b,android.util.Base64.NO_WRAP|android.util.Base64.URL_SAFE|android.util.Base64.NO_PADDING);}
 private synchronized void log(String s){String line=new java.text.SimpleDateFormat("HH:mm:ss",Locale.US).format(new Date())+"  "+s;logs.addLast(line);while(logs.size()>240)logs.removeFirst();}
 private synchronized String logText(){StringBuilder b=new StringBuilder();for(String s:logs)b.append(s).append('\n');return b.length()==0?"Ready.":b.toString();}
 @Override public Response serve(IHTTPSession r){try{String u=r.getUri();if(u==null)u="/";if(u.startsWith("/api/"))return api(r,u);if(u.equals("/media"))return media(r);if(u.equals("/")||u.equals("/index.html"))return asset("web/index.html","text/html; charset=utf-8");if(u.startsWith("/web/"))return asset("web/"+u.substring(5),mime(u));return newFixedLengthResponse(Response.Status.NOT_FOUND,"text/plain","Not found");}catch(Throwable e){log("ERROR "+e.getClass().getSimpleName()+": "+e.getMessage());return jsonError(e.getMessage()==null?e.toString():e.getMessage(),500);}}
 private Response api(IHTTPSession r,String u)throws Exception{
   if(u.equals("/api/info"))return json(obj("session_token",localToken,"version","1.1.0-android","activation_backend",ActivationClient.BASE,"platform","android"));
   if(u.equals("/api/heartbeat"))return json(obj("ok",true));
   if(u.equals("/api/activation/login"))return activationLogin(r);
   if(u.equals("/api/activation/status"))return activationStatus();
   if(u.equals("/api/activation/logout")){ActivationClient.Session old=session;session=null;lastValidated=0;CompletableFuture.runAsync(()->activation.logout(old));return json(obj("ok",true));}
   if(u.equals("/api/settings")){if(r.getMethod()==Method.GET)return json(loadSettings());if(r.getMethod()==Method.POST){JSONObject x=bodyJson(r);saveSettings(x);return json(obj("ok",true));}return method();}
   if(u.equals("/api/library"))return library();
   if(u.equals("/api/upload"))return upload(r);
   if(u.equals("/api/delete"))return delete(r);
   if(u.equals("/api/log"))return json(obj("log",logText()));
   if(u.equals("/api/shutdown"))return json(obj("ok",true));
   if(u.equals("/api/status")){JSONObject s=BroadcastState.json();JSONObject o=new JSONObject();o.put("on_air",s.optBoolean("on_air"));o.put("connected",s.optBoolean("connected"));o.put("bytes_sent",s.optLong("bytes_sent"));o.put("last_error",s.optString("last_error"));o.put("last_error_code",s.optString("last_error").isEmpty()?"":"android_stream_error");return json(o);}
   if(u.equals("/api/streams/status"))return json(BroadcastState.json());
   if(u.equals("/api/streams/test"))return testStream(r);
   if(u.equals("/api/test-connection"))return testStream(r);
   if(u.equals("/api/streams/reconnect")){String id=r.getParms().get("id");Intent i=new Intent(context,BroadcastService.class).setAction(BroadcastService.ACTION_RECONNECT).putExtra(BroadcastService.EXTRA_STREAM_ID,id);context.startService(i);log("Reconnect requested for "+id);return json(obj("ok",true));}
   if(u.equals("/api/streams/stop")||u.equals("/api/broadcast/stop")){Intent i=new Intent(context,BroadcastService.class).setAction(BroadcastService.ACTION_STOP);context.startService(i);return json(obj("ok",true));}
   if(u.equals("/api/streams/start")||u.equals("/api/broadcast/start"))return jsonError("Android device-audio permission must be started through the native Android broadcast button.",409);
   if(u.startsWith("/api/streams/chunk")||u.equals("/api/broadcast/chunk"))return json(obj("ok",true));
   if(u.equals("/api/system-audio/info"))return json(obj("supported",true,"platform","android","sample_rate",48000,"channels",2,"mode","AudioPlaybackCapture / MediaProjection"));
   if(u.equals("/api/system-audio/restart"))return json(obj("ok",true,"message","Android capture follows the broadcast session."));
   if(u.equals("/api/system-audio/pcm"))return jsonError("Android system audio is captured natively during the broadcast session.",409);
   if(u.equals("/api/music/spotify/status"))return json(spotify.status(loadSettings().optString("spotify_client_id","")));
   if(u.equals("/api/music/spotify/connect")){JSONObject o=spotify.connect(loadSettings().optString("spotify_client_id",""),baseUrl());return json(o);}
   if(u.equals("/api/music/spotify/callback")){String h=spotify.callback(r.getParms());return newFixedLengthResponse(Response.Status.OK,"text/html; charset=utf-8",h);}
   if(u.equals("/api/music/spotify/logout"))return json(spotify.logout());
   if(u.equals("/api/music/spotify/library"))return json(spotify.library());
   if(u.equals("/api/music/spotify/playlist"))return json(spotify.playlist(r.getParms().get("id")));
   return jsonError("Unknown Android API route",404);
 }
 private Response activationLogin(IHTTPSession r)throws Exception{if(r.getMethod()!=Method.POST)return method();JSONObject b=bodyJson(r);String user=b.optString("username","").trim(),pass=b.optString("password","");if(user.isEmpty()||pass.isEmpty())return jsonError("Enter your username and password.",400);try{session=activation.login(user,pass);lastValidated=System.currentTimeMillis();log("Activation login accepted for "+session.username);return json(authJson(session));}catch(Exception e){log("Activation login rejected: "+e.getMessage());return jsonError(e.getMessage(),403);}}
 private Response activationStatus(){ActivationClient.Session s=session;if(s==null)return json(obj("authenticated",false,"error","Sign in with an active HABS Broadcaster account to continue."));if(System.currentTimeMillis()-lastValidated>30000){try{if(!activation.validate(s)){session=null;return json(obj("authenticated",false,"error","Your HABS account is no longer active."));}lastValidated=System.currentTimeMillis();}catch(Exception e){/* Keep the existing short-lived session during transient network loss. */}}return json(authJson(s));}
 private static JSONObject authJson(ActivationClient.Session s){JSONObject u=new JSONObject(),o=new JSONObject();try{u.put("username",s.username);u.put("display_name",s.displayName);u.put("status",s.status);o.put("authenticated",true);o.put("token",s.token);o.put("expires_at",s.expiresAt);o.put("user",u);}catch(Exception ignored){}return o;}
 private JSONObject loadSettings(){String raw=context.getSharedPreferences("habs_settings",Context.MODE_PRIVATE).getString("json","");if(raw!=null&&!raw.trim().isEmpty())try{return new JSONObject(raw);}catch(Exception ignored){}JSONObject o=new JSONObject();try{o.put("station_name","My Radio");o.put("port",8000);o.put("mount","/");o.put("bitrate",128);o.put("sample_rate",48000);o.put("channels",2);o.put("connect_timeout",12);o.put("music_volume",1);o.put("mic_volume",1);o.put("system_volume",1);o.put("system_auto_capture",true);o.put("auto_reconnect",true);o.put("reconnect_delay",5);o.put("codec","mp3");o.put("theme","neon");o.put("meter_refresh",60);o.put("auto_next",true);o.put("confirm_quit",true);o.put("streams",new JSONArray());}catch(Exception ignored){}return o;}
 private void saveSettings(JSONObject x){context.getSharedPreferences("habs_settings",Context.MODE_PRIVATE).edit().putString("json",x.toString()).apply();log("Settings saved");}
 private Response library(){JSONArray a=new JSONArray();File[] fs=musicDir.listFiles();if(fs!=null){Arrays.sort(fs,(x,y)->Long.compare(y.lastModified(),x.lastModified()));for(File f:fs)if(f.isFile()&&allowed(f.getName())){JSONObject o=new JSONObject();try{o.put("id",f.getName());o.put("name",f.getName());o.put("size",f.length());o.put("modified",f.lastModified()/1000);}catch(Exception ignored){}a.put(o);}}return json(obj("items",a));}
 private Response upload(IHTTPSession r)throws Exception{if(r.getMethod()!=Method.POST)return method();String name=r.getParms().get("name");name=sanitize(name);if(name.isEmpty()||!allowed(name))return jsonError("Unsupported audio format.",400);long len=-1;try{len=Long.parseLong(r.getHeaders().getOrDefault("content-length","-1"));}catch(Exception ignored){}if(len>1024L*1024*1024)return jsonError("File is too large for the Android library.",413);File dest=unique(name);try(InputStream in=r.getInputStream();OutputStream out=new BufferedOutputStream(new FileOutputStream(dest))){byte[] b=new byte[64*1024];long remain=len;while(true){int want=remain>=0?(int)Math.min(b.length,remain):b.length;if(want==0)break;int n=in.read(b,0,want);if(n<0)break;out.write(b,0,n);if(remain>=0)remain-=n;}}if(dest.length()==0){dest.delete();return jsonError("Empty upload.",400);}log("Imported "+dest.getName());JSONObject item=new JSONObject();item.put("id",dest.getName());item.put("name",dest.getName());item.put("size",dest.length());item.put("modified",dest.lastModified()/1000);return json(obj("ok",true,"item",item));}
 private Response delete(IHTTPSession r)throws Exception{JSONObject b=bodyJson(r);File f=resolve(b.optString("id",""));if(f==null||!f.exists())return jsonError("Track not found.",404);if(!f.delete())return jsonError("Could not delete track.",500);log("Deleted "+f.getName());return json(obj("ok",true));}
 private Response media(IHTTPSession r)throws Exception{File f=resolve(r.getParms().get("id"));if(f==null||!f.exists())return newFixedLengthResponse(Response.Status.NOT_FOUND,"text/plain","Not found");long start=0,end=f.length()-1;String range=r.getHeaders().get("range");boolean partial=false;if(range!=null&&range.startsWith("bytes=")){String[] p=range.substring(6).split("-",2);try{start=Long.parseLong(p[0]);if(p.length>1&&!p[1].isEmpty())end=Long.parseLong(p[1]);partial=true;}catch(Exception ignored){start=0;end=f.length()-1;partial=false;}}start=Math.max(0,Math.min(start,f.length()-1));end=Math.max(start,Math.min(end,f.length()-1));FileInputStream in=new FileInputStream(f);long skipped=0;while(skipped<start){long n=in.skip(start-skipped);if(n<=0)break;skipped+=n;}long length=end-start+1;Response res=newFixedLengthResponse(partial?Response.Status.PARTIAL_CONTENT:Response.Status.OK,mime(f.getName()),in,length);res.addHeader("Accept-Ranges","bytes");res.addHeader("Content-Length",String.valueOf(length));if(partial)res.addHeader("Content-Range","bytes "+start+"-"+end+"/"+f.length());return res;}
 private Response testStream(IHTTPSession r)throws Exception{if(r.getMethod()!=Method.POST)return method();StreamTarget t=StreamTarget.fromJson(bodyJson(r));if(t.host.isEmpty())return jsonError("Enter the streaming server first.",400);if(t.password.isEmpty())return jsonError("Enter the source/DJ password.",400);IcecastSink sink=new IcecastSink(t);long start=System.currentTimeMillis();try{sink.connect();log("Connection test OK: "+t.name+" → "+t.host+":"+t.port);return json(obj("ok",true,"message",("zeno".equals(t.protocol)?"Zeno.fm Icecast":"Source")+" login succeeded in "+(System.currentTimeMillis()-start)+" ms."));}finally{sink.close();}}
 private Response asset(String path,String mime){try{InputStream in=context.getAssets().open(path);int size=in.available();Response r=newFixedLengthResponse(Response.Status.OK,mime,in,size);r.addHeader("Cache-Control","no-cache");return r;}catch(Exception e){return newFixedLengthResponse(Response.Status.NOT_FOUND,"text/plain","Missing asset");}}
 private static String mime(String p){String ext=MimeTypeMap.getFileExtensionFromUrl(p);String m=MimeTypeMap.getSingleton().getMimeTypeFromExtension(ext);if(m!=null)return m;if(p.endsWith(".js"))return "application/javascript; charset=utf-8";if(p.endsWith(".css"))return "text/css; charset=utf-8";if(p.endsWith(".html"))return "text/html; charset=utf-8";return "application/octet-stream";}
 private JSONObject bodyJson(IHTTPSession r)throws Exception{String text=readBody(r,2*1024*1024);return new JSONObject(text.isEmpty()?"{}":text);}
 private String readBody(IHTTPSession r,int max)throws Exception{String lenText=r.getHeaders().get("content-length");int len=-1;try{len=Integer.parseInt(lenText);}catch(Exception ignored){}ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] buf=new byte[8192];int total=0;InputStream in=r.getInputStream();while(total<max&&(len<0||total<len)){int want=len<0?buf.length:Math.min(buf.length,len-total);int n=in.read(buf,0,want);if(n<0)break;b.write(buf,0,n);total+=n;}return b.toString(StandardCharsets.UTF_8.name());}
 private static String sanitize(String s){if(s==null)return"";try{s=Uri.decode(s);}catch(Exception ignored){}s=new File(s).getName().replaceAll("[\\r\\n\\t]","_").trim();return s.length()>180?s.substring(s.length()-180):s;}
 private static boolean allowed(String n){String s=n.toLowerCase(Locale.ROOT);for(String x:new String[]{".mp3",".wav",".flac",".m4a",".aac",".ogg",".opus",".wma",".aiff",".aif",".webm"})if(s.endsWith(x))return true;return false;}
 private File unique(String n){File f=new File(musicDir,n);if(!f.exists())return f;int dot=n.lastIndexOf('.');String a=dot>0?n.substring(0,dot):n,b=dot>0?n.substring(dot):"";for(int i=2;i<9999;i++){f=new File(musicDir,a+" ("+i+")"+b);if(!f.exists())return f;}return new File(musicDir,System.currentTimeMillis()+"-"+n);}
 private File resolve(String id){String n=sanitize(id);if(n.isEmpty())return null;File f=new File(musicDir,n);try{if(!f.getCanonicalPath().startsWith(musicDir.getCanonicalPath()+File.separator))return null;}catch(Exception e){return null;}return f;}
 private static JSONObject obj(Object...kv){JSONObject o=new JSONObject();try{for(int i=0;i+1<kv.length;i+=2)o.put(String.valueOf(kv[i]),kv[i+1]);}catch(Exception ignored){}return o;}
 private static Response json(JSONObject o){Response r=newFixedLengthResponse(Response.Status.OK,"application/json; charset=utf-8",o.toString());r.addHeader("Cache-Control","no-store");return r;}private static Response jsonError(String s,int code){Response.Status st=code==400?Response.Status.BAD_REQUEST:code==401?Response.Status.UNAUTHORIZED:code==403?Response.Status.FORBIDDEN:code==404?Response.Status.NOT_FOUND:code==409?Response.Status.CONFLICT:code==413?Response.Status.REQUEST_ENTITY_TOO_LARGE:Response.Status.INTERNAL_ERROR;JSONObject o=obj("error",s==null?"Error":s,"ok",false);Response r=newFixedLengthResponse(st,"application/json; charset=utf-8",o.toString());r.addHeader("Cache-Control","no-store");return r;}private static Response method(){return jsonError("Method not allowed",405);}
}
