package com.habsradio.broadcaster;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.media.projection.MediaProjectionManager;import android.net.Uri;import android.os.*;import android.view.WindowManager;import android.webkit.*;import org.json.*;import java.net.ServerSocket;

public final class MainActivity extends Activity{
 private static final int REQ_PROJECTION=302,REQ_MIC=303,REQ_FILE=304,REQ_WEB_MIC=305;private WebView web;private LocalServer server;private MediaProjectionManager projectionManager;private String pendingBroadcast="";private ValueCallback<Uri[]> fileCallback;private PermissionRequest webMicRequest;private BroadcastReceiver statusReceiver;
 @Override protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(2,7,5));getWindow().setNavigationBarColor(Color.rgb(2,7,5));projectionManager=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},700);try{server=new LocalServer(this,freePort());}catch(Exception e){showFatal("HABS local engine could not start: "+e.getMessage());return;}setupWebView();registerStatus();web.loadUrl(server.baseUrl()+"/");}
 private static int freePort(){try(ServerSocket s=new ServerSocket(0)){s.setReuseAddress(true);return s.getLocalPort();}catch(Exception e){return 18681;}}
 private void setupWebView(){web=new WebView(this);web.setBackgroundColor(Color.rgb(2,7,5));web.setLayerType(android.view.View.LAYER_TYPE_HARDWARE,null);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setMediaPlaybackRequiresUserGesture(false);s.setAllowFileAccess(true);s.setAllowContentAccess(true);s.setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);s.setSupportMultipleWindows(false);s.setJavaScriptCanOpenWindowsAutomatically(true);s.setUserAgentString(s.getUserAgentString()+" HABS-Broadcaster-Android/1.1.0");CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(web,true);web.addJavascriptInterface(new Bridge(),"HABSAndroid");web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri u=r.getUrl();if(r.isForMainFrame()&&!isLocal(u)){openExternal(u.toString());return true;}return false;}@Override public void onReceivedError(WebView v,WebResourceRequest r,WebResourceError e){if(r.isForMainFrame()&&isLocal(r.getUrl()))v.postDelayed(()->v.loadUrl(server.baseUrl()+"/"),500);}});web.setWebChromeClient(new WebChromeClient(){@Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams p){if(fileCallback!=null)fileCallback.onReceiveValue(null);fileCallback=cb;Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("audio/*");i.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);try{startActivityForResult(i,REQ_FILE);}catch(Exception e){fileCallback=null;cb.onReceiveValue(null);}return true;}@Override public void onPermissionRequest(PermissionRequest request){runOnUiThread(()->{boolean audio=false;for(String r:request.getResources())if(PermissionRequest.RESOURCE_AUDIO_CAPTURE.equals(r))audio=true;if(audio){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED)request.grant(new String[]{PermissionRequest.RESOURCE_AUDIO_CAPTURE});else{webMicRequest=request;requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ_WEB_MIC);}}else request.deny();});}});setContentView(web);}
 private boolean isLocal(Uri u){String h=u.getHost();return "127.0.0.1".equals(h)||"localhost".equalsIgnoreCase(h);}
 private void registerStatus(){statusReceiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){if(web!=null)web.post(()->web.evaluateJavascript("window.HABSAndroidCallbacks&&window.HABSAndroidCallbacks.status&&window.HABSAndroidCallbacks.status()",null));}};IntentFilter f=new IntentFilter(BroadcastService.ACTION_STATUS);if(Build.VERSION.SDK_INT>=33)registerReceiver(statusReceiver,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(statusReceiver,f);}
 private void showFatal(String m){android.widget.TextView t=new android.widget.TextView(this);t.setText("HABS BROADCASTER\n\n"+m);t.setTextColor(Color.WHITE);t.setTextSize(16);t.setPadding(40,80,40,40);t.setBackgroundColor(Color.rgb(2,7,5));setContentView(t);}
 private void openExternal(String url){try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception ignored){}}
 private void continueBroadcastPermission(){try{JSONObject p=new JSONObject(pendingBroadcast);boolean mic=p.optBoolean("mic_enabled",true);if(mic&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ_MIC);return;}startActivityForResult(projectionManager.createScreenCaptureIntent(),REQ_PROJECTION);}catch(Exception e){projectionDenied();}}
 private void projectionDenied(){pendingBroadcast="";BroadcastState.stop("Android device-audio capture permission was not granted");if(web!=null)web.post(()->web.evaluateJavascript("window.HABSAndroidCallbacks&&window.HABSAndroidCallbacks.projectionDenied&&window.HABSAndroidCallbacks.projectionDenied()",null));}
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req==REQ_FILE){ValueCallback<Uri[]> cb=fileCallback;fileCallback=null;if(cb==null)return;if(result!=RESULT_OK||data==null){cb.onReceiveValue(null);return;}Uri[] out;if(data.getClipData()!=null){int n=data.getClipData().getItemCount();out=new Uri[n];for(int i=0;i<n;i++)out[i]=data.getClipData().getItemAt(i).getUri();}else out=data.getData()==null?null:new Uri[]{data.getData()};cb.onReceiveValue(out);return;}if(req==REQ_PROJECTION){if(result!=RESULT_OK||data==null){projectionDenied();return;}try{JSONObject p=new JSONObject(pendingBroadcast);JSONArray streams=p.optJSONArray("streams");Intent svc=new Intent(this,BroadcastService.class).setAction(BroadcastService.ACTION_START);svc.putExtra(BroadcastService.EXTRA_PROJECTION_CODE,result);svc.putExtra(BroadcastService.EXTRA_PROJECTION_DATA,data);svc.putExtra(BroadcastService.EXTRA_TARGETS_JSON,streams==null?"[]":streams.toString());svc.putExtra(BroadcastService.EXTRA_MIC_ENABLED,p.optBoolean("mic_enabled",true));svc.putExtra(BroadcastService.EXTRA_MIC_GAIN,(float)p.optDouble("mic_gain",.65));if(Build.VERSION.SDK_INT>=26)startForegroundService(svc);else startService(svc);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);pendingBroadcast="";}catch(Exception e){projectionDenied();}}}
 @Override public void onRequestPermissionsResult(int req,String[] perms,int[] grants){super.onRequestPermissionsResult(req,perms,grants);if(req==REQ_MIC){if(grants.length>0&&grants[0]==PackageManager.PERMISSION_GRANTED)continueBroadcastPermission();else projectionDenied();}else if(req==REQ_WEB_MIC){PermissionRequest p=webMicRequest;webMicRequest=null;if(p!=null){if(grants.length>0&&grants[0]==PackageManager.PERMISSION_GRANTED)p.grant(new String[]{PermissionRequest.RESOURCE_AUDIO_CAPTURE});else p.deny();}}}
 @Override public void onBackPressed(){if(web!=null&&web.canGoBack())web.goBack();else moveTaskToBack(true);}
 @Override protected void onDestroy(){if(statusReceiver!=null)try{unregisterReceiver(statusReceiver);}catch(Exception ignored){}if(server!=null)server.stop();if(web!=null){web.removeJavascriptInterface("HABSAndroid");web.destroy();}super.onDestroy();}
 public final class Bridge{
   @JavascriptInterface public String startBroadcast(String payload){try{JSONObject p=new JSONObject(payload);JSONArray streams=p.optJSONArray("streams");if(streams==null||streams.length()==0)return new JSONObject().put("ok",false).put("error","No enabled output streams are configured.").toString();pendingBroadcast=p.toString();runOnUiThread(()->continueBroadcastPermission());return new JSONObject().put("ok",true).put("pending",true).toString();}catch(Exception e){try{return new JSONObject().put("ok",false).put("error",e.getMessage()).toString();}catch(Exception x){return"{\"ok\":false}";}}}
   @JavascriptInterface public void stopBroadcast(){runOnUiThread(()->{Intent i=new Intent(MainActivity.this,BroadcastService.class).setAction(BroadcastService.ACTION_STOP);startService(i);getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);});}
   @JavascriptInterface public String getStatus(){return BroadcastState.json().toString();}
   @JavascriptInterface public void openExternal(String url){runOnUiThread(()->MainActivity.this.openExternal(url));}
   @JavascriptInterface public String platform(){return"android";}
   @JavascriptInterface public String version(){return"1.1.0-parity";}
 }
}
