package com.habsradio.broadcaster;

import android.util.Base64;import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;

public final class SpotifyBridge{
 private String access="",refresh="",state="",verifier="",redirect="",clientId="",displayName="",accountId="";private long expiresAt;
 private static String random(int n){byte[] b=new byte[n];new SecureRandom().nextBytes(b);return Base64.encodeToString(b,Base64.NO_WRAP|Base64.URL_SAFE|Base64.NO_PADDING);}private static String challenge(String v)throws Exception{byte[] d=MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.US_ASCII));return Base64.encodeToString(d,Base64.NO_WRAP|Base64.URL_SAFE|Base64.NO_PADDING);}private static String enc(String s){try{return URLEncoder.encode(s,"UTF-8");}catch(Exception e){return s;}}
 public synchronized JSONObject status(String configuredClient){JSONObject o=new JSONObject();try{o.put("connected",!access.isEmpty()||!refresh.isEmpty());o.put("configured",configuredClient!=null&&!configuredClient.trim().isEmpty());o.put("display_name",displayName);o.put("account_id",accountId);}catch(Exception ignored){}return o;}
 public synchronized JSONObject connect(String configuredClient,String base)throws Exception{clientId=configuredClient==null?"":configuredClient.trim();if(clientId.isEmpty())throw new Exception("Spotify Client ID is not configured. Add it in Preferences > Linked Music.");verifier=random(48);state=random(30);redirect=base+"/api/music/spotify/callback";String url="https://accounts.spotify.com/authorize?client_id="+enc(clientId)+"&response_type=code&redirect_uri="+enc(redirect)+"&code_challenge_method=S256&code_challenge="+enc(challenge(verifier))+"&state="+enc(state)+"&scope="+enc("playlist-read-private playlist-read-collaborative user-library-read user-read-private");JSONObject o=new JSONObject();o.put("ok",true);o.put("auth_url",url);o.put("redirect_uri",redirect);return o;}
 public synchronized String callback(Map<String,String> q){try{String err=q.get("error");if(err!=null&&!err.isEmpty())return html(false,"Spotify authorization was cancelled: "+err);String code=q.get("code"),got=q.get("state");if(code==null||got==null||!got.equals(state)||verifier.isEmpty()||clientId.isEmpty())return html(false,"Spotify authorization could not be verified. Return to HABS and try again.");String form="grant_type=authorization_code&code="+enc(code)+"&redirect_uri="+enc(redirect)+"&client_id="+enc(clientId)+"&code_verifier="+enc(verifier);JSONObject t=requestJson("POST","https://accounts.spotify.com/api/token",null,form,"application/x-www-form-urlencoded");access=t.optString("access_token","");if(!t.optString("refresh_token","").isEmpty())refresh=t.optString("refresh_token");expiresAt=System.currentTimeMillis()+t.optInt("expires_in",3600)*1000L;state=verifier="";loadProfile();return html(true,"Spotify is connected. You can return to HABS Broadcaster.");}catch(Exception e){return html(false,"Spotify connection failed: "+e.getMessage());}}
 private synchronized void refreshIfNeeded()throws Exception{if(!access.isEmpty()&&expiresAt-System.currentTimeMillis()>90000)return;if(refresh.isEmpty()||clientId.isEmpty())throw new Exception("Spotify is not connected");String form="grant_type=refresh_token&refresh_token="+enc(refresh)+"&client_id="+enc(clientId);JSONObject t=requestJson("POST","https://accounts.spotify.com/api/token",null,form,"application/x-www-form-urlencoded");access=t.optString("access_token","");if(access.isEmpty())throw new Exception("Spotify refresh returned no access token");if(!t.optString("refresh_token","").isEmpty())refresh=t.optString("refresh_token");expiresAt=System.currentTimeMillis()+t.optInt("expires_in",3600)*1000L;}
 private synchronized JSONObject api(String path)throws Exception{refreshIfNeeded();return requestJson("GET","https://api.spotify.com/v1"+path,"Bearer "+access,null,null);}
 private synchronized void loadProfile(){try{JSONObject p=api("/me");displayName=p.optString("display_name","");accountId=p.optString("id","");}catch(Exception ignored){}}
 public synchronized JSONObject library()throws Exception{JSONObject o=new JSONObject();o.put("playlists",api("/me/playlists?limit=30"));o.put("saved_tracks",api("/me/tracks?limit=30"));return o;}
 public synchronized JSONObject playlist(String id)throws Exception{if(id==null||!id.matches("[A-Za-z0-9]+"))throw new Exception("Invalid Spotify playlist ID");return api("/playlists/"+id+"/items?limit=50");}
 public synchronized JSONObject logout(){access=refresh=state=verifier=redirect=clientId=displayName=accountId="";expiresAt=0;JSONObject o=new JSONObject();try{o.put("ok",true);}catch(Exception ignored){}return o;}
 private static JSONObject requestJson(String method,String url,String bearer,String body,String contentType)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(15000);c.setRequestMethod(method);c.setRequestProperty("Accept","application/json");c.setRequestProperty("User-Agent","HABS-Broadcaster-Android/1.1");if(bearer!=null)c.setRequestProperty("Authorization",bearer);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type",contentType==null?"application/json":contentType);try(OutputStream os=c.getOutputStream()){os.write(body.getBytes(StandardCharsets.UTF_8));}}int code=c.getResponseCode();InputStream in=code>=200&&code<300?c.getInputStream():c.getErrorStream();String text=read(in,4*1024*1024);JSONObject o;try{o=new JSONObject(text.isEmpty()?"{}":text);}catch(Exception e){throw new Exception("Spotify returned an invalid response (HTTP "+code+")");}if(code<200||code>=300){String m=o.optString("error_description","");if(m.isEmpty()){JSONObject er=o.optJSONObject("error");m=er!=null?er.optString("message",""):String.valueOf(o.opt("error"));}throw new Exception(m==null||m.equals("null")||m.isEmpty()?"Spotify API returned "+code:m);}return o;}
 private static String read(InputStream in,int max)throws Exception{if(in==null)return"";ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] buf=new byte[8192];int n,total=0;while((n=in.read(buf))>0&&total<max){b.write(buf,0,n);total+=n;}return b.toString(StandardCharsets.UTF_8.name());}
 private static String html(boolean ok,String msg){String color=ok?"#7cff35":"#ff5b67",title=ok?"Spotify connected":"Spotify connection failed";msg=msg.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;");return "<!doctype html><meta name=viewport content='width=device-width'><style>body{margin:0;background:#050806;color:#eef8ef;font-family:system-ui;display:grid;place-items:center;height:100vh}.c{width:min(520px,88vw);padding:28px;border:1px solid #21472b;border-radius:20px;background:#08110b}.d{width:14px;height:14px;border-radius:50%;background:"+color+";box-shadow:0 0 18px "+color+"}.h{display:flex;gap:12px;align-items:center}p{color:#9bb1a0;line-height:1.6}</style><div class=c><div class=h><i class=d></i><h2>"+title+"</h2></div><p>"+msg+"</p><small>HABS Broadcaster Android</small></div>";}
}
